# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import Categoria_pb2 as proto_dot_Categoria__pb2


class CategoriaServiceStub(object):
    """METODOS PARA CONSUMIR 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.addCategoria = channel.unary_unary(
                '/CategoriaService/addCategoria',
                request_serializer=proto_dot_Categoria__pb2.CategoriaDTO.SerializeToString,
                response_deserializer=proto_dot_Categoria__pb2.CategoriaObjDTO.FromString,
                )
        self.getCategoria = channel.unary_unary(
                '/CategoriaService/getCategoria',
                request_serializer=proto_dot_Categoria__pb2.GetCategoriaRequest.SerializeToString,
                response_deserializer=proto_dot_Categoria__pb2.CategoriaObjDTO.FromString,
                )


class CategoriaServiceServicer(object):
    """METODOS PARA CONSUMIR 
    """

    def addCategoria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCategoria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CategoriaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'addCategoria': grpc.unary_unary_rpc_method_handler(
                    servicer.addCategoria,
                    request_deserializer=proto_dot_Categoria__pb2.CategoriaDTO.FromString,
                    response_serializer=proto_dot_Categoria__pb2.CategoriaObjDTO.SerializeToString,
            ),
            'getCategoria': grpc.unary_unary_rpc_method_handler(
                    servicer.getCategoria,
                    request_deserializer=proto_dot_Categoria__pb2.GetCategoriaRequest.FromString,
                    response_serializer=proto_dot_Categoria__pb2.CategoriaObjDTO.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CategoriaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CategoriaService(object):
    """METODOS PARA CONSUMIR 
    """

    @staticmethod
    def addCategoria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CategoriaService/addCategoria',
            proto_dot_Categoria__pb2.CategoriaDTO.SerializeToString,
            proto_dot_Categoria__pb2.CategoriaObjDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getCategoria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CategoriaService/getCategoria',
            proto_dot_Categoria__pb2.GetCategoriaRequest.SerializeToString,
            proto_dot_Categoria__pb2.CategoriaObjDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
