# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Receta.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/Receta.proto\"U\n\tRecetaDTO\x12\x10\n\x08idReceta\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x11\n\tidUsuario\x18\x03 \x01(\x05\x12\x13\n\x0bidCategoria\x18\x04 \x01(\x05\"$\n\x10GetRecetaRequest\x12\x10\n\x08idReceta\x18\x01 \x01(\x05\"1\n\x14RecetaServerResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\"Y\n\x0cRecetaObjDTO\x12\x1a\n\x06receta\x18\x01 \x01(\x0b\x32\n.RecetaDTO\x12-\n\x0eserverResponse\x18\x02 \x01(\x0b\x32\x15.RecetaServerResponse\"[\n\rListRecetaDTO\x12\x1b\n\x07recetas\x18\x01 \x03(\x0b\x32\n.RecetaDTO\x12-\n\x0eserverResponse\x18\x02 \x01(\x0b\x32\x15.RecetaServerResponse2f\n\rRecetaService\x12&\n\taddReceta\x12\n.RecetaDTO\x1a\r.RecetaObjDTO\x12-\n\tgetReceta\x12\x11.GetRecetaRequest\x1a\r.RecetaObjDTOb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.Receta_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RECETADTO']._serialized_start=22
  _globals['_RECETADTO']._serialized_end=107
  _globals['_GETRECETAREQUEST']._serialized_start=109
  _globals['_GETRECETAREQUEST']._serialized_end=145
  _globals['_RECETASERVERRESPONSE']._serialized_start=147
  _globals['_RECETASERVERRESPONSE']._serialized_end=196
  _globals['_RECETAOBJDTO']._serialized_start=198
  _globals['_RECETAOBJDTO']._serialized_end=287
  _globals['_LISTRECETADTO']._serialized_start=289
  _globals['_LISTRECETADTO']._serialized_end=380
  _globals['_RECETASERVICE']._serialized_start=382
  _globals['_RECETASERVICE']._serialized_end=484
# @@protoc_insertion_point(module_scope)
