# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import Receta_pb2 as proto_dot_Receta__pb2


class RecetaServiceStub(object):
    """METODOS PARA CONSUMIR 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.addReceta = channel.unary_unary(
                '/RecetaService/addReceta',
                request_serializer=proto_dot_Receta__pb2.RecetaDTO.SerializeToString,
                response_deserializer=proto_dot_Receta__pb2.RecetaObjDTO.FromString,
                )
        self.getReceta = channel.unary_unary(
                '/RecetaService/getReceta',
                request_serializer=proto_dot_Receta__pb2.GetRecetaRequest.SerializeToString,
                response_deserializer=proto_dot_Receta__pb2.RecetaObjDTO.FromString,
                )


class RecetaServiceServicer(object):
    """METODOS PARA CONSUMIR 
    """

    def addReceta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getReceta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecetaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'addReceta': grpc.unary_unary_rpc_method_handler(
                    servicer.addReceta,
                    request_deserializer=proto_dot_Receta__pb2.RecetaDTO.FromString,
                    response_serializer=proto_dot_Receta__pb2.RecetaObjDTO.SerializeToString,
            ),
            'getReceta': grpc.unary_unary_rpc_method_handler(
                    servicer.getReceta,
                    request_deserializer=proto_dot_Receta__pb2.GetRecetaRequest.FromString,
                    response_serializer=proto_dot_Receta__pb2.RecetaObjDTO.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RecetaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RecetaService(object):
    """METODOS PARA CONSUMIR 
    """

    @staticmethod
    def addReceta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RecetaService/addReceta',
            proto_dot_Receta__pb2.RecetaDTO.SerializeToString,
            proto_dot_Receta__pb2.RecetaObjDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getReceta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RecetaService/getReceta',
            proto_dot_Receta__pb2.GetRecetaRequest.SerializeToString,
            proto_dot_Receta__pb2.RecetaObjDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
